# Generated by Django 2.0rc1 on 2018-01-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='accessibility',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='bathrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='docents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='entry_cost',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='food_options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='open_to_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='place',
            name='parking',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='pet_policy',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='visitor_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
