# Generated by Django 2.0rc1 on 2018-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180116_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='accessibility',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parking',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='pet_policy',
            field=models.TextField(blank=True),
        ),
    ]
