# Generated by Django 2.0rc1 on 2018-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20180116_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='radius_km',
            field=models.FloatField(default=0.5),
        ),
    ]
