language: python

python:
  - 3.6

services: postgresql

env:
  - DATABASE_URL=postgres://postgres:@localhost/travisci

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic

script:
  - python manage.py test
