# Generated by Django 2.1.5 on 2019-01-21 23:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_placepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='placepage',
            name='accessibility_and_safety',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='placepage',
            name='bathrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placepage',
            name='directions',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='docents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placepage',
            name='dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placepage',
            name='entry_cost',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='placepage',
            name='food_options',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placepage',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placepage',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placepage',
            name='open_to_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='parking',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='pet_policy',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='placepage',
            name='radius_km',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='placepage',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='placepage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='placepage',
            name='visitor_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placepage',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='home.Station'),
        ),
    ]
