# Generated by Django 2.1.5 on 2019-01-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190121_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placepage',
            name='station',
        ),
        migrations.RemoveField(
            model_name='placepage',
            name='url',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
