# Generated by Django 2.1.5 on 2019-01-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190121_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='placepage',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
