# Generated by Django 2.1.5 on 2019-01-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190121_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placepage',
            name='name',
        ),
    ]
