# Generated by Django 2.1.5 on 2019-01-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_placepage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepage',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='home.Station'),
        ),
    ]
